name: "Contexts"

on:
  push:
    branches:
      - main

jobs:
  my-contexts:
    runs-on: ubuntu-latest
    steps:
      - name: "My step"
        env:
          MY_REPO: ${{ github.repository }}
          MY_ACTOR: ${{ github.actor }}
        run: |
          echo "This is my repo: $MY_REPO"
          echo "I'm $MY_ACTOR"