name: Build, Test, and Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy application
        run: echo "First job - Deploying to production"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build application
        run: echo "Second job - Building the application"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test application
        run: echo "Third job - Running tests"