on:
  schedule:
    - cron: '*/2 * * * *'
    #- cron: '30 5 * * 1,3'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      # - name: Not on Monday or Wednesday
      #   if: github.event.schedule != '30 5 * * 1,3'
      #   run: echo "Skip this step on Monday and Wednesday"
      - name: Every time
        run: echo "The current server time is $(date)"